# Generated by Django 4.2.16 on 2026-04-21 12:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Candidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("full_name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone", models.CharField(blank=True, max_length=30)),
                ("country", models.CharField(blank=True, max_length=100)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("region", models.CharField(blank=True, max_length=100)),
                (
                    "remote_preference",
                    models.CharField(
                        choices=[
                            ("onsite", "On-site"),
                            ("remote", "Remote"),
                            ("hybrid", "Hybrid"),
                            ("flexible", "Flexible"),
                        ],
                        default="flexible",
                        max_length=20,
                    ),
                ),
                ("current_title", models.CharField(blank=True, max_length=255)),
                ("years_of_experience", models.FloatField(default=0.0)),
                (
                    "seniority_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("intern", "Intern"),
                            ("junior", "Junior"),
                            ("mid", "Mid-level"),
                            ("senior", "Senior"),
                            ("lead", "Lead"),
                            ("principal", "Principal"),
                            ("director", "Director"),
                            ("executive", "Executive"),
                        ],
                        max_length=20,
                    ),
                ),
                ("summary", models.TextField(blank=True)),
                (
                    "highest_education",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("high_school", "High School"),
                            ("associate", "Associate"),
                            ("bachelor", "Bachelor's"),
                            ("master", "Master's"),
                            ("phd", "PhD"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                ("education_field", models.CharField(blank=True, max_length=255)),
                (
                    "availability_status",
                    models.CharField(
                        choices=[
                            ("actively_looking", "Actively Looking"),
                            ("open", "Open to Opportunities"),
                            ("not_looking", "Not Looking"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                (
                    "expected_salary_min",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
                ),
                (
                    "expected_salary_max",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
                ),
                ("salary_currency", models.CharField(default="USD", max_length=10)),
                ("gender", models.CharField(blank=True, max_length=30)),
                ("age_range", models.CharField(blank=True, max_length=20)),
                ("ethnicity", models.CharField(blank=True, max_length=100)),
                ("disability_status", models.BooleanField(null=True)),
                ("is_synthetic", models.BooleanField(default=False)),
                ("raw_cv_text", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="candidate_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "candidates_candidate",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CandidateExperience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("job_title", models.CharField(max_length=255)),
                ("company", models.CharField(blank=True, max_length=255)),
                ("location", models.CharField(blank=True, max_length=255)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("is_current", models.BooleanField(default=False)),
                ("description", models.TextField(blank=True)),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="experiences",
                        to="candidates.candidate",
                    ),
                ),
            ],
            options={
                "db_table": "candidates_experience",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="CandidateEmbedding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("vector", models.JSONField()),
                ("model_name", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "candidate",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="embedding",
                        to="candidates.candidate",
                    ),
                ),
            ],
            options={
                "db_table": "candidates_embedding",
            },
        ),
        migrations.CreateModel(
            name="CandidateCV",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("file", models.FileField(upload_to="cvs/%Y/%m/")),
                ("original_filename", models.CharField(max_length=255)),
                ("file_type", models.CharField(max_length=10)),
                ("raw_text", models.TextField(blank=True)),
                ("is_primary", models.BooleanField(default=False)),
                ("parsed_at", models.DateTimeField(blank=True, null=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cvs",
                        to="candidates.candidate",
                    ),
                ),
            ],
            options={
                "db_table": "candidates_cv",
            },
        ),
        migrations.CreateModel(
            name="CandidateSkill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("skill_name", models.CharField(max_length=200)),
                ("skill_category", models.CharField(blank=True, max_length=100)),
                (
                    "proficiency",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                            ("expert", "Expert"),
                        ],
                        max_length=20,
                    ),
                ),
                ("years_used", models.FloatField(blank=True, null=True)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("cv_parsed", "CV Parsed"),
                            ("manual", "Manual"),
                            ("inferred", "Inferred"),
                        ],
                        default="cv_parsed",
                        max_length=20,
                    ),
                ),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skills",
                        to="candidates.candidate",
                    ),
                ),
            ],
            options={
                "db_table": "candidates_skill",
                "unique_together": {("candidate", "skill_name")},
            },
        ),
    ]
