# Generated by Django 4.2.16 on 2026-07-08 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0001_initial"),
        ("candidates", "0002_candidate_sourced_by_organization"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidate",
            name="sourced_by_organization",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sourced_candidates",
                to="organizations.organization",
            ),
        ),
    ]
