# Generated by Django 4.2.16 on 2026-07-08 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("candidates", "0003_alter_candidate_sourced_by_organization"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidate",
            name="source",
            field=models.CharField(blank=True, default="", max_length=30),
        ),
    ]
