# Generated by Django 4.2.16 on 2026-07-08 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("candidates", "0004_candidate_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidate",
            name="external_id",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
