# Generated by Django 4.2.16 on 2026-04-21 12:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="JobPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("company", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("requirements", models.TextField(blank=True)),
                ("responsibilities", models.TextField(blank=True)),
                ("country", models.CharField(blank=True, max_length=100)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("region", models.CharField(blank=True, max_length=100)),
                (
                    "work_model",
                    models.CharField(
                        choices=[("onsite", "On-site"), ("remote", "Remote"), ("hybrid", "Hybrid")],
                        default="onsite",
                        max_length=20,
                    ),
                ),
                ("industry", models.CharField(blank=True, max_length=100)),
                ("job_function", models.CharField(blank=True, max_length=100)),
                (
                    "employment_type",
                    models.CharField(
                        choices=[
                            ("full_time", "Full-time"),
                            ("part_time", "Part-time"),
                            ("contract", "Contract"),
                            ("internship", "Internship"),
                            ("freelance", "Freelance"),
                        ],
                        default="full_time",
                        max_length=20,
                    ),
                ),
                (
                    "experience_level",
                    models.CharField(
                        choices=[
                            ("entry", "Entry Level"),
                            ("mid", "Mid Level"),
                            ("senior", "Senior Level"),
                            ("lead", "Lead / Principal"),
                            ("executive", "Executive"),
                        ],
                        default="mid",
                        max_length=20,
                    ),
                ),
                (
                    "salary_min",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
                ),
                (
                    "salary_max",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
                ),
                ("salary_currency", models.CharField(default="USD", max_length=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("closed", "Closed"),
                            ("filled", "Filled"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("posted_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateField(blank=True, null=True)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("manual", "Manual"),
                            ("adzuna", "Adzuna"),
                            ("jooble", "Jooble"),
                            ("the_muse", "The Muse"),
                            ("synthetic", "Synthetic"),
                            ("kaggle", "Kaggle"),
                        ],
                        default="manual",
                        max_length=30,
                    ),
                ),
                ("external_id", models.CharField(blank=True, max_length=255)),
                ("external_url", models.URLField(blank=True)),
                ("is_synthetic", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "jobs_jobpost",
                "ordering": ["-posted_at", "-created_at"],
                "unique_together": {("source", "external_id")},
            },
        ),
        migrations.CreateModel(
            name="JobEmbedding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("vector", models.JSONField()),
                ("model_name", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "job",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="embedding",
                        to="jobs.jobpost",
                    ),
                ),
            ],
            options={
                "db_table": "jobs_embedding",
            },
        ),
        migrations.CreateModel(
            name="JobSkillRequirement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("skill_name", models.CharField(max_length=200)),
                ("skill_category", models.CharField(blank=True, max_length=100)),
                ("is_required", models.BooleanField(default=True)),
                ("min_years", models.FloatField(blank=True, null=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skill_requirements",
                        to="jobs.jobpost",
                    ),
                ),
            ],
            options={
                "db_table": "jobs_skill_requirement",
                "unique_together": {("job", "skill_name")},
            },
        ),
    ]
