# Generated by Django 4.2.16 on 2026-04-21 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobpost",
            name="city",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="jobpost",
            name="country",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="jobpost",
            name="industry",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="jobpost",
            name="job_function",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="jobpost",
            name="region",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
