# Generated by Django 4.2.16 on 2026-07-07 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0001_initial"),
        ("jobs", "0002_alter_jobpost_city_alter_jobpost_country_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobpost",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="jobs",
                to="organizations.organization",
                db_constraint=False,
            ),
        ),
    ]
