# Generated by Django 4.2.16 on 2026-07-08 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0001_initial"),
        ("jobs", "0004_backfill_default_organization"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobpost",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="jobs",
                to="organizations.organization",
            ),
        ),
    ]
