# Generated by Django 4.2.16 on 2026-07-08 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0006_alter_jobpost_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobpost",
            name="content_hash",
            field=models.CharField(blank=True, db_index=True, default="", max_length=64),
        ),
    ]
