# Generated by Django 4.2.16 on 2026-07-09 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0007_jobpost_content_hash"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobpost",
            name="required_education",
            field=models.CharField(
                blank=True,
                choices=[
                    ("high_school", "High School"),
                    ("associate", "Associate"),
                    ("bachelor", "Bachelor's"),
                    ("master", "Master's"),
                    ("phd", "PhD"),
                ],
                default="",
                max_length=20,
            ),
        ),
    ]
