# Generated by Django 4.2.16 on 2026-07-09 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0008_jobpost_required_education"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobpost",
            name="source",
            field=models.CharField(
                choices=[
                    ("manual", "Manual"),
                    ("adzuna", "Adzuna"),
                    ("jooble", "Jooble"),
                    ("the_muse", "The Muse"),
                    ("synthetic", "Synthetic"),
                    ("kaggle", "Kaggle"),
                    ("emscad", "EMSCAD (Kaggle)"),
                    ("jobsam", "jobs.am (Kaggle)"),
                    ("linkedin", "LinkedIn Job Postings (Kaggle)"),
                    ("djinni", "Djinni (HuggingFace)"),
                    ("openintro", "Audit Study 2004 (OpenIntro)"),
                ],
                default="manual",
                max_length=30,
            ),
        ),
    ]
