# Generated by Django 4.2.16 on 2026-04-21 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("matching", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExplanationReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[("shap", "SHAP"), ("lime", "LIME")], default="shap", max_length=10
                    ),
                ),
                ("feature_importances", models.JSONField(default=dict)),
                ("top_positive_factors", models.JSONField(default=list)),
                ("top_negative_factors", models.JSONField(default=list)),
                ("missing_skills", models.JSONField(default=list)),
                ("summary_text", models.TextField(blank=True)),
                ("generated_at", models.DateTimeField(auto_now=True)),
                ("model_version", models.CharField(default="v1", max_length=50)),
                (
                    "match_result",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="explanation",
                        to="matching.matchresult",
                    ),
                ),
            ],
            options={
                "db_table": "explainability_report",
            },
        ),
    ]
