# Generated by Django 4.2.16 on 2026-04-21 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("explainability", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="explanationreport",
            name="matching_skills",
            field=models.JSONField(default=list),
        ),
    ]
