# Generated by Django 4.2.16 on 2026-04-21 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("explainability", "0002_explanationreport_matching_skills"),
    ]

    operations = [
        migrations.AlterField(
            model_name="explanationreport",
            name="method",
            field=models.CharField(
                choices=[("shap", "SHAP"), ("lime", "LIME"), ("combined", "Combined")],
                default="combined",
                max_length=10,
            ),
        ),
    ]
