# Generated by Django 4.2.16 on 2026-04-21 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FairnessReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("protected_attribute", models.CharField(max_length=50)),
                ("report_data", models.JSONField(default=dict)),
                ("disparate_impact_ratio", models.FloatField(blank=True, null=True)),
                ("selection_rate_overall", models.FloatField(blank=True, null=True)),
                ("bias_flag", models.BooleanField(default=False)),
                ("generated_at", models.DateTimeField(auto_now=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fairness_reports",
                        to="jobs.jobpost",
                    ),
                ),
            ],
            options={
                "db_table": "fairness_report",
                "ordering": ["-generated_at"],
                "unique_together": {("job", "protected_attribute")},
            },
        ),
        migrations.CreateModel(
            name="SubgroupMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("group_value", models.CharField(max_length=100)),
                ("total_candidates", models.IntegerField(default=0)),
                ("shortlisted_count", models.IntegerField(default=0)),
                ("selection_rate", models.FloatField(default=0.0)),
                ("avg_match_score", models.FloatField(blank=True, null=True)),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subgroups",
                        to="fairness.fairnessreport",
                    ),
                ),
            ],
            options={
                "db_table": "fairness_subgroup",
                "unique_together": {("report", "group_value")},
            },
        ),
    ]
