# Generated by Django 4.2.16 on 2026-07-08 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fairness", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="fairnessreport",
            name="basis",
            field=models.CharField(
                choices=[
                    ("actual_decisions", "Actual hiring decisions"),
                    (
                        "ai_rank_provisional",
                        "AI ranking (provisional -- no decisions recorded yet)",
                    ),
                ],
                default="ai_rank_provisional",
                max_length=25,
            ),
        ),
    ]
