# Generated by Django 4.2.16 on 2026-04-21 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="IngestionRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("adzuna", "Adzuna"),
                            ("jooble", "Jooble"),
                            ("the_muse", "The Muse"),
                            ("kaggle", "Kaggle"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("done", "Done"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("query", models.CharField(blank=True, max_length=255)),
                ("location", models.CharField(blank=True, max_length=100)),
                ("country_code", models.CharField(default="gb", max_length=5)),
                ("jobs_fetched", models.IntegerField(default=0)),
                ("jobs_created", models.IntegerField(default=0)),
                ("jobs_skipped", models.IntegerField(default=0)),
                ("error_message", models.TextField(blank=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "ingestion_run",
                "ordering": ["-created_at"],
            },
        ),
    ]
