# Generated by Django 4.2.16 on 2026-04-21 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("candidates", "0001_initial"),
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MatchBatchRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("done", "Done"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("candidates_processed", models.IntegerField(default=0)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="match_runs",
                        to="jobs.jobpost",
                    ),
                ),
            ],
            options={
                "db_table": "matching_batch_run",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MatchResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("overall_score", models.FloatField()),
                ("semantic_score", models.FloatField(default=0.0)),
                ("skill_overlap_score", models.FloatField(default=0.0)),
                ("experience_score", models.FloatField(default=0.0)),
                ("education_score", models.FloatField(default=0.0)),
                ("rank", models.IntegerField(blank=True, null=True)),
                ("model_version", models.CharField(default="v1", max_length=50)),
                ("computed_at", models.DateTimeField(auto_now=True)),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="match_results",
                        to="candidates.candidate",
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="match_results",
                        to="jobs.jobpost",
                    ),
                ),
            ],
            options={
                "db_table": "matching_result",
                "ordering": ["-overall_score"],
                "unique_together": {("candidate", "job")},
            },
        ),
    ]
