# Generated by Django 4.2.16 on 2026-07-07 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="application",
            options={"ordering": ["-applied_at"]},
        ),
        migrations.RemoveField(
            model_name="application",
            name="education_score",
        ),
        migrations.RemoveField(
            model_name="application",
            name="experience_score",
        ),
        migrations.RemoveField(
            model_name="application",
            name="overall_match_score",
        ),
        migrations.RemoveField(
            model_name="application",
            name="rank",
        ),
        migrations.RemoveField(
            model_name="application",
            name="semantic_score",
        ),
        migrations.RemoveField(
            model_name="application",
            name="skill_overlap_score",
        ),
    ]
