# Generated by Django 4.2.16 on 2026-07-09 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0003_applicationstatushistory"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicationstatushistory",
            name="candidate_percentile_at_decision",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="applicationstatushistory",
            name="is_override",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
