# Generated by Django 4.2.16 on 2026-04-21 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PipelineSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("date", models.DateField()),
                ("total_applications", models.IntegerField(default=0)),
                ("screened_count", models.IntegerField(default=0)),
                ("shortlisted_count", models.IntegerField(default=0)),
                ("interview_count", models.IntegerField(default=0)),
                ("offer_count", models.IntegerField(default=0)),
                ("hired_count", models.IntegerField(default=0)),
                ("rejected_count", models.IntegerField(default=0)),
                ("avg_match_score", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snapshots",
                        to="jobs.jobpost",
                    ),
                ),
            ],
            options={
                "db_table": "analytics_pipeline_snapshot",
                "ordering": ["-date"],
                "unique_together": {("job", "date")},
            },
        ),
    ]
