# Generated by Django 4.2.16 on 2026-04-21 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SkillTaxonomy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("canonical_name", models.CharField(max_length=200)),
                ("category", models.CharField(max_length=100)),
                ("subcategory", models.CharField(blank=True, max_length=100)),
                ("aliases", models.JSONField(default=list)),
                ("description", models.TextField(blank=True)),
                ("is_technical", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("related_skills", models.ManyToManyField(blank=True, to="taxonomy.skilltaxonomy")),
            ],
            options={
                "verbose_name_plural": "Skill Taxonomies",
                "db_table": "taxonomy_skill",
                "ordering": ["category", "name"],
            },
        ),
        migrations.CreateModel(
            name="JobRoleTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=200, unique=True)),
                ("industry", models.CharField(blank=True, max_length=100)),
                ("typical_education", models.CharField(blank=True, max_length=30)),
                ("typical_experience_years", models.FloatField(default=0.0)),
                ("description", models.TextField(blank=True)),
                (
                    "core_skills",
                    models.ManyToManyField(
                        blank=True, related_name="core_roles", to="taxonomy.skilltaxonomy"
                    ),
                ),
            ],
            options={
                "db_table": "taxonomy_job_role",
                "ordering": ["title"],
            },
        ),
    ]
