# Generated by Django 4.2.16 on 2026-07-07 12:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("taxonomy", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PendingSkill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("proposed_name", models.CharField(max_length=200)),
                ("category", models.CharField(blank=True, max_length=100)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("esco_sync", "ESCO Sync"),
                            ("corpus_mining", "Corpus Mining"),
                            ("user_submitted", "User Submitted"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "source_detail",
                    models.CharField(
                        blank=True,
                        help_text="e.g. ESCO concept URI, or 'seen in 6 job postings'",
                        max_length=255,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("similarity_score", models.FloatField(blank=True, null=True)),
                ("similarity_match_type", models.CharField(blank=True, max_length=20)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_pending_skills",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "similar_existing_skill",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pending_duplicates",
                        to="taxonomy.skilltaxonomy",
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="submitted_pending_skills",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "taxonomy_pending_skill",
                "ordering": ["-created_at"],
            },
        ),
    ]
